# Generated by Django 4.0.6 on 2022-08-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primApp', '0003_usuarios_imagen_alter_mascotas_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='edad',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='vacunas',
            field=models.TextField(max_length=60),
        ),
    ]
