# Generated by Django 4.0.6 on 2022-08-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primApp', '0004_alter_mascotas_edad'),
        ('primApp', '0004_alter_mascotas_edad_alter_mascotas_vacunas'),
    ]

    operations = [
    ]
